### ISSUE TITLE
It's impossible to subscribe to topic after unsubscribing

### ISSUE THREAD

**Issue by stairs** [forresthopkinsa/StompProtocolAndroid#3]
Topics are not removed from `mTopics` map on unsubscribe. Therefore we get "Attempted to subscribe to already-subscribed path!" error when trying to subscribe again. The fix seems to be pretty easy. 
Though I would still suggest automatic resubscribing to topics when sockets are connected.

**Comment by forresthopkinsa** [comment]
Thanks for finding this! I'll publish a fix tomorrow.

**Comment by stairs** [comment]
Many thanks for a quick response!

**Comment by forresthopkinsa** [comment]
Sorry I didn't publish a fix on Friday, I forgot that it wasn't a workday. I'll release a fix tomorrow, once I'm back at my work computer. Sorry for the wait.

**Comment by stairs** [comment]
NP. Thanks for letting us know!

**Comment by forresthopkinsa** [comment]
Let me know if that fix doesn't work

**Comment by stairs** [comment]
There is a small problem with it. You're removing destination before fetching topic id. Therefore it will always result in an error when unsubscribing with null id.

**Comment by forresthopkinsa** [comment]
Okay, yeah, I've started testing that commit and I see the problem. That was a dumb move on my part, I should have been paying more attention haha

**Comment by forresthopkinsa** [comment]
I've been pretty busy at work -- can you let me know whether this works for you? Committing the obvious fix now...

**Comment by stairs** [comment]
Thanks! I have no problem with resubscribing now. However, now after each re-connect, I receive more and more duplicate messages somehow :D I'll try to understand how `share()` operator works and come up with a fix. Please, advise if you see the solution at once.

**Comment by stairs** [comment]
Got it. We just don't disconnect from `messages()` on `disconnect()`. Therefore each new `connect()` will result in `callSubscribers()` executed as many times as `connect()` was called.

**Comment by stairs** [comment]
If you can give an access I'll create a PR with the fix.

**Comment by forresthopkinsa** [comment]
Duplicate messages? Interesting. I've seen that before, but I had fixed it then. Good find!

Could you make a separate issue for it? Then we can work on a PR. Thanks!
