### ISSUE TITLE
Duplicate messages on re-connect

### ISSUE THREAD

**Issue by stairs** [forresthopkinsa/StompProtocolAndroid#4]
It appears that we just don't unsubscribe from `messages()` on `disconnect()`. Therefore each new `connect()` will result in `callSubscribers()` executed as many times as `connect()` was called.

**Comment by forresthopkinsa** [comment]
Good catch! I don't know how I haven't experienced this myself. Anyway, we can work together on a PR if you want, or I can work on that.

If you want to do it, you don't need any special permissions; you can open a PR even if you're not a repository contributor.

**Comment by forresthopkinsa** [comment]
Problem solved. I'll keep my eye on this issue and re-open if it crops up again. Thanks for the help @stairs !!
